version: 2.1
executors:
  build-executor:
    docker:
      - image: cimg/node:lts
      
orbs:
  node: circleci/node@4.7.0
  
jobs:
  build-check:
    environment:
      TOKEN: ODM3NTEyNTU4NTA4Mzc2MTE3.YItoWg.ZdzdZFQlK8NMh30WFB7wrNqg5Wo
      METADATA_REFRESH_INTERVAL_MINUTES: 60
      PROD_CHANNEL_ACTIVITY_ALL: 859521842317754369
      GOOGLE_AUTH_DETAILS: "{}"
    executor: build-executor
    steps:
      - checkout
      - run: |
          npm install
          npm start

workflows:
  build-workflow:
    jobs:
      - build-check